### ISSUE TITLE
mate-power-manager: brightness UI broken when used under non-compositing window manager

### ISSUE THREAD

**Issue by lexa2** [mate-desktop/mate-power-manager#110]
After I had updated from mate 1.6 to 1.8 I have no meaningfull UI when press keys to change laptop screen brightness or laptop keyboard backlight brightness. All I get is a tiny grey square at the middle of the active display.

Looking at the mate-power-manager source code I suspected that something might got broken in the  non-compositing draw codepath for 1.8. I had tried to enable marco's built-in desktop compositing and it fixed the issue.

At the same time OSD popup with non-compositing codepath works great in mate-settings-daemon (i.e. I got normal "classic" popups when press volume change keys) so it most probably is a regression in mate-power-daemon OSD handling.

Packages I use and their versions:
```
ii  mate-power-manager                                          1.8.0+dfsg1-3+b2                  amd64        power management tool for the MATE desktop
ii  mate-power-manager-common                                   1.8.0+dfsg1-3                     all          power management tool for the MATE desktop (common files)
ii  mate-settings-daemon                                        1.8.1-2                           all          MATE session settings daemon (metapackage)
ii  mate-settings-daemon-common                                 1.8.1-2                           all          MATE session settings daemon (common files)
ii  mate-settings-daemon-pulse                                  1.8.1-2                           amd64        MATE session settings daemon (PulseAudio version)
```

**Comment by NiceandGently** [comment]
Can we revert https://github.com/mate-desktop/mate-power-manager/commit/4fd2ae34e50e63ef562356f804dbdea81341f4e2
for 1.8 branch?
It makes no sense to include a bug in a stable branch if no one fix it.

**Comment by lurwas** [comment]
Nazonight, your tweak helped me a bit on the way. Now I can see the brightness controls going up and down.
But...the actual brightness of the display is not changed :(
(This is on a HP EliteBook).

Anyone got a fix for this yet?

**Comment by nachanon** [comment]
An alternative approach is to fix the object name in `acme.ui` script directly. I found no other code in mate-power-manager that tried to use `acme_frame` or `acme_vbox` from `acme.ui`, so there shouldn't be a problem.

Regarding the excess border issue, I compared it to mate-settings-daemon's `acme.ui` GTKBuilder script (`/usr/share/mate-settings-daemon/acme.ui`), and found that mate-settings-daemon's one does not have a nested GTKFrame container, it uses GTKVBox `acme_box` directly inside GTKWindow.

mate-power-manager's one _does have_ the corresponding GTKVBox container, but it was named `acme_vbox` rather than `acme_box`, and has an additional 12-pixel border width.

So, this is an alternative patch which fixes GTKVBox object name, removes the excess border, and eliminates the unnecessary GTKFrame:
https://gist.github.com/nachanon/2c3f43a30bdab1786fd3

Following screenshot is captured after applied this alternative patch:
![](https://cloud.githubusercontent.com/assets/5958794/5646492/842dd47a-96af-11e4-9664-09901b2e534a.png)

You'd see that backlight popup is now displayed properly with progress bar and icon, and looked consistent with all other media key popup dialogs.

For users that didn't want to recompile mate-power-manager, can use the following patch to fix the already-installed `/usr/share/mate-power-manager/acme.ui` script directly as well:
https://gist.github.com/nachanon/458ea39d53518d63f87c

Then just logout and re-login to see the result.

MATE: MATE Power Manager 1.8.0, MATE 1.8.1 (patched against source package from Debian Wheezy backports repository)
System: Debian GNU/Linux 7.0 Wheezy i386

**Comment by NiceandGently** [comment]
I can confirm that 1003_fix-backlight-popup.patch works.
But using the other patches for acme.ui gives me always a square as osd.
Which is the right acme.ui patch for using together with 1003_fix-backlight-popup.patch?

**Comment by NiceandGently** [comment]
Using the merged version  of the patch https://github.com/mate-desktop/mate-power-manager/commit/a7d224c53ce2555fc675d689b35d01728eaf7b4e
fix the issue for me.

**Comment by lexa2** [comment]
acme.ui patch works for me. Thanks nachanon et al for your work on fixing this issue.

**Comment by freed00m** [comment]
https://gist.github.com/nachanon/458ea39d53518d63f87c helped me in linux mint 17.1, thanks you :) @nachanon

**Comment by prankurgit** [comment]
Nachanon .. thanks man .. the patch works out of the box .. awesum stuff :+1:
